/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:783523:
  appc.background(230);
} //_CODE_:window1:783523:

public void uploadButtonPressed(GButton source, GEvent event) { //_CODE_:uploadButton:690952:
  inputMainButton();
} //_CODE_:uploadButton:690952:

public void resizeSliderChanged(GSlider source, GEvent event) { //_CODE_:resizeSlider:413428:
  resizeNum = resizeSlider.getValueI();
} //_CODE_:resizeSlider:413428:

public void transparencySliderChanged(GSlider source, GEvent event) { //_CODE_:transparencySlider:283265:
  transparencyNum = transparencySlider.getValueI();
} //_CODE_:transparencySlider:283265:

public void startButtonPressed(GButton source, GEvent event) { //_CODE_:startButton:349027:
  startButton();
} //_CODE_:startButton:349027:

public void builderButtonPressed(GButton source, GEvent event) { //_CODE_:builderButton:430356:
  inputBuilderButton();
} //_CODE_:builderButton:430356:

public void widthtextChanged(GTextField source, GEvent event) { //_CODE_:widthtext:330580:
  mainImageWidth = parseInt(widthtext.getText());
  changeDimensions();
} //_CODE_:widthtext:330580:

public void heighttextChnaged(GTextField source, GEvent event) { //_CODE_:heighttext:853244:
  mainImageHeight = parseInt(heighttext.getText());
  changeDimensions();
} //_CODE_:heighttext:853244:

public void resetButtonPressed(GButton source, GEvent event) { //_CODE_:resetButton:405092:
  resetButton();
} //_CODE_:resetButton:405092:

public void saveButtonPresed(GButton source, GEvent event) { //_CODE_:saveButton:354441:
  saveButton();
} //_CODE_:saveButton:354441:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Photo Mosaic GUI", 0, 0, 600, 400, JAVA2D);
  window1.noLoop();
  window1.addDrawHandler(this, "win_draw1");
  label1 = new GLabel(window1, 100, 20, 140, 40);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Upload Base Image");
  label1.setOpaque(false);
  uploadButton = new GButton(window1, 130, 60, 80, 30);
  uploadButton.setText("UPLOAD");
  uploadButton.addEventHandler(this, "uploadButtonPressed");
  resizeSlider = new GSlider(window1, 100, 280, 140, 60, 10.0);
  resizeSlider.setShowValue(true);
  resizeSlider.setLimits(12, 1, 50);
  resizeSlider.setNbrTicks(10);
  resizeSlider.setShowTicks(true);
  resizeSlider.setNumberFormat(G4P.INTEGER, 0);
  resizeSlider.setOpaque(false);
  resizeSlider.addEventHandler(this, "resizeSliderChanged");
  label2 = new GLabel(window1, 100, 110, 140, 40);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Transparency Amount");
  label2.setOpaque(false);
  transparencySlider = new GSlider(window1, 100, 150, 140, 60, 10.0);
  transparencySlider.setShowValue(true);
  transparencySlider.setLimits(127.0, 0.0, 255.0);
  transparencySlider.setNbrTicks(6);
  transparencySlider.setShowTicks(true);
  transparencySlider.setNumberFormat(G4P.DECIMAL, 0);
  transparencySlider.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  transparencySlider.setOpaque(false);
  transparencySlider.addEventHandler(this, "transparencySliderChanged");
  label3 = new GLabel(window1, 100, 240, 140, 40);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("Size of Builder Images");
  label3.setOpaque(false);
  label4 = new GLabel(window1, 400, 200, 140, 40);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Generate Mosiac");
  label4.setOpaque(false);
  startButton = new GButton(window1, 400, 250, 140, 50);
  startButton.setText("START");
  startButton.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  startButton.addEventHandler(this, "startButtonPressed");
  label5 = new GLabel(window1, 400, 20, 140, 40);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("Upload Builder Images");
  label5.setOpaque(false);
  builderButton = new GButton(window1, 430, 60, 80, 30);
  builderButton.setText("UPLOAD");
  builderButton.addEventHandler(this, "builderButtonPressed");
  label6 = new GLabel(window1, 400, 110, 140, 40);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Resolution");
  label6.setOpaque(false);
  widthtext = new GTextField(window1, 350, 150, 90, 30, G4P.SCROLLBARS_NONE);
  widthtext.setPromptText("100");
  widthtext.setOpaque(true);
  widthtext.addEventHandler(this, "widthtextChanged");
  heighttext = new GTextField(window1, 500, 150, 90, 30, G4P.SCROLLBARS_NONE);
  heighttext.setPromptText("100");
  heighttext.setOpaque(true);
  heighttext.addEventHandler(this, "heighttextChnaged");
  label7 = new GLabel(window1, 440, 150, 60, 30);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("X");
  label7.setOpaque(false);
  resetButton = new GButton(window1, 400, 320, 140, 50);
  resetButton.setText("RESET");
  resetButton.setLocalColorScheme(GCScheme.RED_SCHEME);
  resetButton.addEventHandler(this, "resetButtonPressed");
  saveButton = new GButton(window1, 340, 260, 50, 30);
  saveButton.setText("SAVE");
  saveButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  saveButton.addEventHandler(this, "saveButtonPresed");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GLabel label1; 
GButton uploadButton; 
GSlider resizeSlider; 
GLabel label2; 
GSlider transparencySlider; 
GLabel label3; 
GLabel label4; 
GButton startButton; 
GLabel label5; 
GButton builderButton; 
GLabel label6; 
GTextField widthtext; 
GTextField heighttext; 
GLabel label7; 
GButton resetButton; 
GButton saveButton; 